{% set name = "percy" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/percy-{{ version }}.tar.gz
  sha256: 6238612dc401fa5c221c0ad7738f7ea43e48fe2695f6423e785ee2bc940f021d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests >=2.14.0

test:
  imports:
    - percy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/percy/python-percy-client
  summary: Python client library for visual regression testing with Percy (https://percy.io).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
